### ISSUE TITLE
Data purge does not happen if application is dead/constantly restarting

### ISSUE THREAD

**Issue by lifeeth** [resin-io/resin-supervisor#412] opened 2017-03-29 09:27 UTC
If the user pushes a faulty application causing the container to constantly restart, there is no way to purge the data. This is probably because of the following line which executes the purge after killing the application.

https://github.com/resin-io/resin-supervisor/blob/master/src/api.coffee#L106

**Comment by pcarranzav** [comment] 2017-03-29 18:02
@lifeeth what supervisor and OS version? That line shouldn't cause trouble because the kill operation should succeed if the container is stopped. Unless there's some sort of race condition we haven't seen before.

Do you get any error messages?

**Comment by lifeeth** [comment] 2017-03-29 19:26
More details -> https://forums.resin.io/t/app-container-has-vanished/713

**Comment by pcarranzav** [comment] 2017-10-21 03:31
Looking at that forum thread, the device logs posted there show that the purge *did* happen, but the application was failing to start because the container command wasn't found (i.e. the program pointed to by the image's CMD doesn't exist). This is expected behavior (albeit maybe a bit confusing), yet it's possible that SD card corruption caused the command to "disappear". This would not be a supervisor issue in any case, so I'm closing this.

**Closed by pcarranzav** 2017-10-21 03:31 UTC
