### ISSUE TITLE
Application stopped before download completed caused by many subsequent git pushes

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-supervisor#243] opened 2016-08-24 18:49 UTC
As it appears, running many `git push` commands in a short period of time may cause the application to be killed before the download completed, leaving the device in a weird state.

Example log:

```
23.08.16 22:08:17 [-0300] Downloading application 'registry.resin.io/octopustest/494f5ffe3b0234015986908212c6b934e501d34a'

23.08.16 22:08:17 [-0300] Killing application 'registry.resin.io/octopus/2a2cb10c98ec36b9b8f4c79e691a0b1fd3a4c110'

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:17 [-0300] Running in a container, ignoring fstab swap entry for /swapfile.

23.08.16 22:08:27 [-0300]

23.08.16 22:08:28 [-0300] Killed application 'registry.resin.io/octopus/2a2cb10c98ec36b9b8f4c79e691a0b1fd3a4c110'
```

**Comment by pcarranzav** [comment] 2016-10-14 16:57
Has anyone been able to reproduce this? Closing this in the meantime. I haven't been able to reproduce after months of git pushing a variety of apps in a variety of frequencies to the supervisor. 
I can't see what would bring up this behavior other than two supervisor containers running on the device at the same time, an obscure race condition with an app restart API request (which somehow caused the update locking to fail?) or some other sort of dark magic. Moreover, the application update code has changed a great deal since this was reported.

Please reopen if this behavior is ever seen again (but we'll need supervisor/docker logs and probably device access to debug).

**Closed by pcarranzav** 2016-10-14 16:57 UTC
