### ISSUE TITLE
Can't reboot via the supervisor.

### ISSUE THREAD

**Issue by zvin** [resin-io/resin-supervisor#497] opened 2017-09-06 13:33 UTC
2 users are reporting a similar issue:
https://app.frontapp.com/open/cnv_772ssz
https://app.frontapp.com/open/cnv_76ncon

flowdock thread: https://www.flowdock.com/app/rulemotion/resin-devices/threads/Aeqp7CicHkwXrrpU1nwoEmSrgEA

The device doesn't reboot when asked to via the supervisor.

Sshing in the device and running `reboot` works.
![screen shot 2017-09-05 at 1 13 35 pm 2](https://user-images.githubusercontent.com/180331/30114721-e7cd4a20-9318-11e7-87ec-c4a3fcef8509.png)

Maybe related systemd issue: https://github.com/systemd/systemd/issues/2925

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2bvn)

**Comment by pcarranzav** [comment] 2017-09-06 18:19
It appears that the cause for this (as investigated by @floion) is that the container's systemd is stepping on the host's dbus socket. The fix should come from here https://github.com/resin-io-library/base-images/issues/336 - so I'm closing this one.

**Closed by pcarranzav** 2017-09-06 18:19 UTC
