### ISSUE TITLE
various errors due to '[object Object]'

### ISSUE THREAD

**Issue by emirotin** [resin-io/resin-supervisor#474] opened 2017-07-19 10:57 UTC
Supervisor 5.1.0
```
19.07.17 13:52:52 (+0300) Killing application 'registry2.resin.io/forex3/03eed94c8d6091eea551ded1c18e8b8448262aa4'
19.07.17 13:53:06 (+0300) Failed to kill application 'registry2.resin.io/forex3/03eed94c8d6091eea551ded1c18e8b8448262aa4' due to '[object Object]'
19.07.17 13:53:14 (+0300) Failed to download application 'registry2.resin.io/forex3/17f1876b6fc97150215ca98035fcd5361360369a' due to '[object Object]'
19.07.17 13:53:37 (+0300) Downloading delta for application 'registry2.resin.io/forex3/17f1876b6fc97150215ca98035fcd5361360369a'
19.07.17 13:54:06 (+0300) Failed to download application 'registry2.resin.io/forex3/17f1876b6fc97150215ca98035fcd5361360369a' due to '[object Object]'
```

Maybe related to deltas

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2gaz)

**Comment by lurch** [comment] 2017-07-19 11:20
Ping @jviotti @Shou - is this in any way related to the errors we were having, or is "object Object" just a generic malformed error message that could come from anywhere?

**Comment by jviotti** [comment] 2017-07-19 12:55
Maybe the supervisor is accidentally treating error objects incorrectly for some cases (like corvus did)?

**Comment by pcarranzav** [comment] 2017-08-08 17:10
If anyone sees this again, please post supervisor logs or send me leech output

**Comment by imrehg** [comment] 2017-09-23 07:26
@pcarranzav seems like another instance of this. Pinged in front and attached full leech.

After supervisor restart, the application cannot start with this error:

```
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]: [2017-09-23T07:20:26.432Z] Error starting apps: { Error: (HTTP code 500) server error - invalid character 'c' looking for beginning of value
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at /usr/src/app/dist/app.js:374:214635
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at /usr/src/app/dist/app.js:374:214598
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at m.buildPayload (/usr/src/app/dist/app.js:374:214608)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at IncomingMessage.<anonymous> (/usr/src/app/dist/app.js:374:214114)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at emitNone (events.js:91:20)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at IncomingMessage.emit (events.js:185:7)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at endReadableNT (_stream_readable.js:974:12)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:     at process._tickCallback (internal/process/next_tick.js:98:9)
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:   reason: 'server error',
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:   statusCode: 500,
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]:   json: { message: 'invalid character \'c\' looking for beginning of value' } }
Sep 23 07:20:26 dd326f9 start-resin-supervisor[4504]: [2017-09-23T07:20:26.440Z] Event: Start application update poll {"interval":60000}
```

and in the dashboard it shows:
```
23.09.17 10:20:25 (+0300) Installing application 'XXXX'
23.09.17 10:20:25 (+0300) Installed application 'XXXX'
23.09.17 10:20:25 (+0300) Starting application 'XXXX'
23.09.17 10:20:26 (+0300) Failed to start application 'XXXX' due to '[object Object]'
```
and the application does not start.

**Comment by pcarranzav** [comment] 2017-09-25 22:51
That last instance of the error is due to an out of memory situation that leaves docker in a bad state.  This was being investigated by @zozo123 but it's out of the scope of the supervisor - will have to be dealt with at the OS level.

Other instances may have been caused by the issue solved by https://github.com/resin-io/resin-supervisor/pull/496 - and in any case the incorrect logging of "object Object" should be fixed by https://github.com/resin-io/resin-supervisor/pull/490 - so I'm closing this, please reopen if you see this on a supervisor > v6.2.9.

**Closed by pcarranzav** 2017-09-25 22:51 UTC

**Comment by imrehg** [comment] 2017-10-19 15:11
@pcarranzav what was the fix for this last one? there's another device that comes up like this, and neither rebooting docker, nor rebooting the device solve it...

**Comment by pcarranzav** [comment] 2017-12-19 08:59
For future reference -  devices showing this error might be doing so for a variety of reasons - the log is shown like this due to a bug that only affects the logging of errors. Support agents should identify the true  underlying cause of the error and act accordingly.
If the error on the supervisor logs shows "container not found", then the workaround is to delete  the supervisor's database and restart the supervisor. A supervisor update should also fix these cases and is a permanent fix.
If the logs show the `invalid character 'c'` message, then the problem is actually at the docker or balena level - for some reason the engine is failing to report errors correctly. In these cases the underlying issue and fix can be a variety of things - we've seen cases where this was due to not enough memory, and other cases where something was wrong in the image (for instance, the Dockerfile had put a file in /data) so the container couldn't be started.
