### ISSUE TITLE
lockfile directory can disappear

### ISSUE THREAD

**Issue by petrosagg** [resin-io/resin-supervisor#409] opened 2017-03-28 18:19 UTC
![17521588_10210382480053005_1217137813_o 1](https://cloud.githubusercontent.com/assets/939420/24420622/23d401fe-13fc-11e7-86ec-a269189cad96.png)

**Comment by pcarranzav** [comment] 2017-03-29 18:23
I've been looking at this and can't find why it could happen. afaict docker always creates bind mount paths before starting the container. Any steps to reproduce @petrosagg? Maybe more info from this particular case, like docker journald logs? Or even the application and supervisor logs from before this happened?

**Comment by pcarranzav** [comment] 2018-03-15 20:11
Closing this since it would've been a docker/balena issue (the daemon is supposed to create bind-mounted directories) and we haven't been able to reproduce, and balena has been updated several times since. Please reopen if it's reproduced with resinOS > 2.12.3 / supervisor > 7.1.14. But even in that case the issue should probably go in github.com/resin-os/balena

**Closed by pcarranzav** 2018-03-15 20:11 UTC
