### ISSUE TITLE
update lockfile ignored on kill/delete-then-download strategies

### ISSUE THREAD

**Issue by curcuz** [resin-io/resin-supervisor#350] opened 2016-11-22 13:19 UTC
# Context
* ResinOS: `1.20.0`
* Supervisor: `2.8.2`
* Deltas: `enabled`
* Update strategy: `kill-then-download` or `delete-then-download`

# Action

1. from the container, run `touch /data/resin-updates.lock`
2. push an update 

# Expected behaviour

the supervisor should wait for lock release/override before killing/deleting the old container and proceed with the update

# What actually happens

the supervisor ignores the lockfile, kills/deletes the old container and proceeds with the update

**Comment by pcarranzav** [comment] 2016-11-22 17:34
Sounds very weird... as the supervisor does take the lock before killing in *all* the update strategies (see [here](https://github.com/resin-io/resin-supervisor/blob/master/src/application.coffee#L482)). I'll try to reproduce, but did you check that the lockfile wasn't there before touching it? (i.e. maybe an update was already pending and the supervisor had taken the lock already)
Did this happen consistently every time?

**Comment by pcarranzav** [comment] 2018-03-15 20:21
Closing this since I haven't been able to reproduce, it's been a very long time, and the whole update process has changed drastically with #482 - please reopen if this happens again in > 7.1.14, with detailed supervisor logs if possible.

Also, using `touch` to create the lockfile is not supported, since the lockfile might already be there (created by the supervisor if it's in the middle of an update).

**Closed by pcarranzav** 2018-03-15 20:21 UTC
