### ISSUE TITLE
The off-line response of the /device api should include the commit hash

### ISSUE THREAD

**Issue by BrianAdams** [resin-io/resin-supervisor#461] opened 2017-06-27 02:37 UTC
When a device is off-line the /device api still returns a response.  That response is currently missing the commit hash of the running container.  The information is available locally and it seems reasonable that it should be returned with the response even if the vpn connection to the resin data api's is unavailable.

Example off-line response:
```
{
  "ip_address": "10.1.1.182 192.168.254.1",
  "api_port": 48484,
  "os_version": "Resin OS 2.0.0-beta.7",
  "supervisor_version": "3.0.1",
  "download_progress": null,
  "update_pending": false,
  "update_failed": false,
  "update_downloaded": false
}
```

**Comment by pcarranzav** [comment] 2017-07-17 15:54
Good catch @BrianAdams, thanks. The problem is not that the device is offline, but that the state the supervisor API returns is only set when an update happens. This will get fixed with the refactor I'm doing in #465.

**Closed** 2018-03-07 13:37 UTC
