### ISSUE TITLE
Unique key constraint violated

### ISSUE THREAD

**Issue by telphan** [resin-io/resin-supervisor#670] opened 2018-06-01 11:02 UTC
This bug prevents any control over the user container.

```
Jun 01 10:11:01 6c3b082 healthdog[10047]: [2018-06-01T10:11:01.622Z] Error reporting initial configuration, will retry { t: Unique key constraint violated
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at /usr/src/app/dist/app.js:387:252909
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at u (/usr/src/app/dist/app.js:9:72709)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromiseFromHandler (/usr/src/app/dist/app.js:305:143488)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromise (/usr/src/app/dist/app.js:305:144388)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromise0 (/usr/src/app/dist/app.js:305:145087)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromises (/usr/src/app/dist/app.js:305:146414)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._fulfill (/usr/src/app/dist/app.js:305:145457)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at s._resolve (/usr/src/app/dist/app.js:305:154371)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at s._promiseFulfilled (/usr/src/app/dist/app.js:305:154712)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at s._iterate (/usr/src/app/dist/app.js:305:154192)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at s.t [as _init] (/usr/src/app/dist/app.js:305:153413)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromise (/usr/src/app/dist/app.js:305:144426)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromise0 (/usr/src/app/dist/app.js:305:145087)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._settlePromises (/usr/src/app/dist/app.js:305:146414)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at A._fulfill (/usr/src/app/dist/app.js:305:145457)
Jun 01 10:11:01 6c3b082 healthdog[10047]:     at H._callback (/usr/src/app/dist/app.js:114:22879)
Jun 01 10:11:01 6c3b082 healthdog[10047]:   message: 'Unique key constraint violated',
Jun 01 10:11:01 6c3b082 healthdog[10047]:   statusCode: 404,
Jun 01 10:11:01 6c3b082 healthdog[10047]:   name: 't' }
```

**Comment by pcarranzav** [comment] 2018-08-17 18:28
This was fixed in https://github.com/resin-io/resin-supervisor/pull/612

The cause: RESIN_HOST_LOG_TO_DISPLAY is deprecated, and is filtered out in the target state endpoint, but the supervisor still tries to report it when it starts the first time. So the workaround is to remove the RESIN_HOST_LOG_TO_DISPLAY variable from the app.

Supervisors with version >= 7.5.4 shouldn't be affected by this (so another workaround is OS update).

**Closed by pcarranzav** 2018-08-17 18:28 UTC
Labels: High priority, type/bug
