### ISSUE TITLE
The supervisor should never delete persistent user-data

### ISSUE THREAD

**Issue by TimJay** [resin-io/resin-supervisor#600] opened 2018-03-23 08:30 UTC
When one switches between applications in the new multi-container environment based on balena volumes, the old application data is permanently deleted from the device.

With the old behaviour, nothing in /mnt/data/resin-data/APPID ever got touched. Through the host-access data could me copied or moved between applications and /data contents would re-appear when switching back to a previous application.

The new behaviour was not announced and there were no warnings, thus it resulted in permanent loss of valuable data.

Resin OS 2.12.3+rev1
Supervisor 7.1.14

**Comment by pcarranzav** [comment] 2018-04-17 00:40
Hi! I'm very sorry to hear you experienced data loss. The fact that data from an old app was kept when moving to a different app was undocumented behavior which we've always considered a bug (see #110) - It's not a behaviour we've encouraged users to rely on, and especially using host access to move data between apps. That said, we should've clearly been more explicit about this, and we definitely should've warned about this change of behavior in the UI.

For most users, the data from the old app would cause problems in resource-limited devices because it would take up space and be impossible to purge. We're considering a feature to migrate data when moving between apps, and will work to make the documentation and UI clearer, but I'll close this issue in the meantime as deleting user data when moving between apps is by design and not a bug.

By the way, if you're moving between applications often - is it possible you would be better off using [staged releases](https://github.com/resin-io-playground/staged-releases) instead? This is the preferred way to keep devices at different versions of the same application.

**Closed by pcarranzav** 2018-04-17 00:40 UTC
